// Generated by Unloop
// Smart Coffee Machine

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_brew_clicked(|| {
        println!("brew clicked");
    });
    
    app.on_clean_clicked(|| {
        println!("clean clicked");
    });
    

    
    app.run()
}
